#!/usr/bin/env python3
"""Generate shared agent entries and exhaustive human repository views."""

from __future__ import annotations

import argparse
import ast
import json
import math
import re
import subprocess
import sys
from pathlib import Path
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from change_guard import _matches_pattern, load_contract, matching_roles  # noqa: E402
from compile_registry import atomic_write  # noqa: E402
from registry_runtime import build_manifest  # noqa: E402


MODEL_PATH = Path("protocols/repository/DOCUMENTATION.json")
GENERATED_NOTICE = "<!-- Generated by scripts/compile_repository_views.py. Do not edit directly. -->"
MAX_SUMMARY_CHARS = 180


class ViewError(RuntimeError):
    pass


def load_model(root: Path = ROOT) -> dict[str, Any]:
    try:
        model = json.loads((root / MODEL_PATH).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ViewError(f"cannot read {MODEL_PATH}: {type(exc).__name__}") from exc
    if model.get("version") != 1:
        raise ViewError("unsupported documentation model version")
    for key in ("areas", "agent_entries", "human_outputs", "packages"):
        if key not in model:
            raise ViewError(f"documentation model is missing {key}")
    return model


def _git_paths(root: Path, *args: str) -> list[str]:
    completed = subprocess.run(
        ["git", *args, "-z"], cwd=root, capture_output=True, check=False
    )
    if completed.returncode:
        message = completed.stderr.decode("utf-8", errors="replace").strip()
        raise ViewError(message or f"git {' '.join(args)} failed")
    return sorted(
        item
        for item in completed.stdout.decode("utf-8", errors="surrogateescape").split("\0")
        if item
    )


def _excluded(path: str, model: dict[str, Any]) -> bool:
    return any(_matches_pattern(path, pattern) for pattern in model.get("exclusions", []))


def repository_paths(root: Path, model: dict[str, Any]) -> list[str]:
    # Human views describe tracked files plus untracked additions that already
    # resolve to a declared repository role. Arbitrary scratch files therefore
    # cannot make generated documentation stale, while a legitimate new source
    # can enter the maintenance transaction before it is staged.
    paths = {
        path
        for path in _git_paths(root, "ls-files")
        if (root / path).exists() or (root / path).is_symlink()
    }
    contract = load_contract(root)
    paths.update(
        path
        for path in _git_paths(root, "ls-files", "--others", "--exclude-standard")
        if matching_roles(path, contract)
    )
    paths.add(MODEL_PATH.as_posix())
    paths.add(Path(__file__).relative_to(root).as_posix())
    paths.add(model["agent_entries"]["common"])
    paths.update(model["agent_entries"]["outputs"].keys())
    paths.update(model["agent_entries"]["outputs"].values())
    paths.update(model["human_outputs"].values())
    return sorted(path for path in paths if not _excluded(path, model))


def _strip_frontmatter(text: str) -> str:
    if not text.startswith("---\n"):
        return text.strip()
    end = text.find("\n---\n", 4)
    if end < 0:
        raise ViewError("entry source has unclosed YAML frontmatter")
    return text[end + 5 :].strip()


def _clean_summary(text: str) -> str:
    cleaned = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    cleaned = re.sub(r"\[\[([^\]|]+)(?:\|[^\]]+)?\]\]", r"\1", cleaned)
    cleaned = re.sub(r"[`*#>]", "", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    if len(cleaned) > MAX_SUMMARY_CHARS:
        cleaned = cleaned[: MAX_SUMMARY_CHARS - 1].rstrip() + "…"
    return cleaned


def _markdown_summary(path: Path) -> str | None:
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None
    body = _strip_frontmatter(text) if text.startswith("---\n") else text
    heading = re.search(r"^#\s+(.+)$", body, flags=re.MULTILINE)
    body = re.sub(r"```.*?```", "", body, flags=re.DOTALL)
    paragraphs = re.split(r"\n\s*\n", body)
    explanation = ""
    for paragraph in paragraphs:
        value = paragraph.strip()
        if not value or value.startswith(("#", "```", "<!--", "Back:", "Back to", "Return to")):
            continue
        explanation = value
        break
    parts = [heading.group(1) if heading else "", explanation]
    summary = _clean_summary(" — ".join(part for part in parts if part))
    return summary or None


def _python_summary(path: Path) -> str | None:
    try:
        module = ast.parse(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, SyntaxError):
        return None
    doc = ast.get_docstring(module, clean=True)
    return _clean_summary(doc.splitlines()[0]) if doc else None


def _javascript_summary(path: Path) -> str | None:
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None
    match = re.search(r"/\*\*?\s*(.*?)\*/", text, flags=re.DOTALL)
    return _clean_summary(match.group(1)) if match else None


def _area(path: str, model: dict[str, Any]) -> dict[str, str] | None:
    matches = [
        area
        for area in model["areas"]
        if path == area["path"] or path.startswith(area["path"].rstrip("/") + "/")
    ]
    return max(matches, key=lambda item: len(item["path"])) if matches else None


def _purpose(
    relative: str,
    *,
    root: Path,
    model: dict[str, Any],
    route_by_path: dict[str, dict[str, Any]],
) -> str:
    override = model.get("artifact_overrides", {}).get(relative)
    if override:
        return override
    route = route_by_path.get(relative)
    if route:
        return route["description"]
    path = root / relative
    if path.is_symlink():
        area = _area(relative, model)
        return area["purpose"] if area else "Declared symbolic-link entry."
    if path.is_file():
        summary = None
        if path.suffix.lower() == ".md":
            summary = _markdown_summary(path)
        elif path.suffix.lower() == ".py":
            summary = _python_summary(path)
        elif path.suffix.lower() == ".js":
            summary = _javascript_summary(path)
        if summary:
            return summary
    area = _area(relative, model)
    if area:
        return area["purpose"]
    if relative.startswith("."):
        return "Repository configuration or support metadata."
    raise ViewError(f"no human explanation can be derived for repository path: {relative}")


def _audience(path: str, model: dict[str, Any]) -> str:
    if path == "AGENTS.md" or path.startswith("adapters/codex/"):
        return "Codex"
    if path == "CLAUDE.md" or path.startswith("adapters/claude/"):
        return "Claude"
    if path == "README.md" or path.startswith("docs/human/"):
        return "Human"
    package = _package_for_path(path, model)
    if package and package.get("traversal") == "repository" and Path(path).name == "README.md":
        return "Human"
    if package and "/codex/" in path:
        return "Codex"
    if package and "/claude/" in path:
        return "Claude"
    return "Shared"


def _package_for_path(path: str, model: dict[str, Any]) -> dict[str, Any] | None:
    matches = [
        package
        for package in model["packages"]
        if path == package["path"] or path.startswith(package["path"].rstrip("/") + "/")
    ]
    return max(matches, key=lambda package: len(package["path"])) if matches else None


def _is_external_pointer(path: str, model: dict[str, Any]) -> bool:
    package = _package_for_path(path, model)
    return bool(package and package.get("traversal") == "none")


def _kind(path: str, generated: set[str], roles: list[str], model: dict[str, Any]) -> str:
    if path in generated:
        return "generated"
    if path == "theory-reference":
        return "submodule"
    if _is_external_pointer(path, model):
        return "external pointer"
    if "skill-source" in roles:
        return "skill source"
    if "test-source" in roles:
        return "verification"
    if "human-guide" in roles:
        return "explanation"
    if path.endswith(("CONTRACT.json", "DOCUMENTATION.json")):
        return "canonical contract"
    return "source/support"


def _escape(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def _link_from_human(path: str) -> str:
    return f"../../{path}"


def _file_cell(path: str, model: dict[str, Any]) -> str:
    if _is_external_pointer(path, model):
        return f"`{_escape(path)}`"
    return f"[{_escape(path)}]({_link_from_human(path)})"


def render_agent_entries(root: Path, model: dict[str, Any]) -> dict[str, str]:
    common_path = root / model["agent_entries"]["common"]
    common = _strip_frontmatter(common_path.read_text(encoding="utf-8"))
    outputs: dict[str, str] = {}
    for output, overlay_path in sorted(model["agent_entries"]["outputs"].items()):
        overlay = _strip_frontmatter((root / overlay_path).read_text(encoding="utf-8"))
        outputs[output] = (
            f"{GENERATED_NOTICE}\n\n{common.rstrip()}\n\n{overlay.rstrip()}\n"
        )
    return outputs


def render_repository_index(
    root: Path,
    model: dict[str, Any],
    contract: dict[str, Any],
    manifest: dict[str, Any],
) -> str:
    generated = {
        *model["agent_entries"]["outputs"].keys(),
        *model["human_outputs"].values(),
        *contract.get("generated_outputs", {}).keys(),
    }
    route_by_path = {route["path"]: route for route in manifest["routes"]}
    rows: list[str] = []
    for relative in repository_paths(root, model):
        roles = [role["id"] for role in matching_roles(relative, contract)]
        purpose = _purpose(
            relative, root=root, model=model, route_by_path=route_by_path
        )
        role_text = ", ".join(roles) if roles else "repository-contained"
        rows.append(
            "| "
            + f"{_file_cell(relative, model)} | "
            + f"{_escape(purpose)} | {_kind(relative, generated, roles, model)} | "
            + f"{_audience(relative, model)} | {_escape(role_text)} |"
        )
    return (
        "---\n"
        "audience: human\n"
        "authority: generated-explanatory-only\n"
        "agent_read_policy: explicit-human-guide-task-or-doc-sync-only\n"
        "generated: true\n"
        "---\n\n"
        f"{GENERATED_NOTICE}\n\n"
        "# Live Repository Index\n\n"
        "Back to the [repository atlas](08_REPOSITORY_ATLAS.md). This exhaustive "
        "reference is generated from Git, the repository contract, registry metadata, "
        "file introductions, and deterministic fallbacks. It explains files but never "
        "overrides their canonical content.\n\n"
        "| File | What it means | Kind | Audience | Maintenance role |\n"
        "|---|---|---|---|---|\n"
        + "\n".join(rows)
        + "\n"
    )


def _route_kind(path: str, model: dict[str, Any]) -> str:
    if path.startswith("design-with-claude/"):
        return "single-file"
    if path.startswith("theory-reference/"):
        return "submodule package"
    if _is_external_pointer(path, model):
        return "external pointer"
    return "packaged skill"


def _token_estimate(path: Path, relative: str, model: dict[str, Any] | None = None) -> str:
    active_model = model or load_model(ROOT)
    if _is_external_pointer(relative, active_model) or path.is_symlink() or not path.is_file():
        return "—"
    return str(math.ceil(path.stat().st_size / 4))


def _package_paths(root: Path, package: dict[str, Any], main_paths: Iterable[str]) -> list[str]:
    prefix = package["path"].rstrip("/")
    traversal = package["traversal"]
    if traversal == "none":
        return []
    if traversal == "repository":
        return sorted(path for path in main_paths if path.startswith(prefix + "/"))
    if traversal == "declared-submodule":
        submodule = root / prefix
        if not submodule.is_dir():
            raise ViewError(f"declared submodule is unavailable: {prefix}")
        return [f"{prefix}/{path}" for path in _git_paths(submodule, "ls-files")]
    raise ViewError(f"unsupported package traversal: {traversal}")


def _package_file_role(path: str) -> str:
    name = Path(path).name
    if name == "README.md":
        return "Human orientation for the package."
    if name == "SKILL.md":
        return "Skill entry or shared workflow instructions."
    if name in {"AGENTS.md", "CLAUDE.md", "CODEX.md"} or "/codex/" in path:
        return "Platform wrapper or platform metadata."
    if "/shared/phases/" in path:
        return "Phase-specific instructions loaded only for that operation."
    if "/shared/rules/" in path:
        return "Reusable constraint shared by multiple phases."
    if "/shared/templates/" in path:
        return "Reusable output template."
    if "/scripts/" in path:
        return "Deterministic support, installation, synchronization, or validation script."
    if name == "protocol.json":
        return "Canonical machine-readable protocol."
    return "Package support file."


def render_skill_catalog(root: Path, model: dict[str, Any], manifest: dict[str, Any]) -> str:
    visible_states = {"active", "manual", "off"}
    rows: list[str] = []
    for route in manifest["routes"]:
        if route["state"] not in visible_states:
            continue
        triggers = ", ".join(route.get("triggers", [])) or "family triggers"
        source = route["path"]
        rows.append(
            "| "
            + f"{_escape(route['id'])} | {_escape(route['family'])} | {_escape(route['state'])} | "
            + f"{_escape(route['description'])} | {_escape(triggers)} | "
            + f"{_escape(route.get('not_for', ''))} | {_route_kind(source, model)} | "
            + f"{_file_cell(source, model)} | {_token_estimate(root / source, source, model)} |"
        )

    main_paths = repository_paths(root, model)
    package_sections: list[str] = []
    for package in model["packages"]:
        package_sections.extend(
            [
                f"## {_escape(package['id'])}",
                "",
                f"**Type:** `{_escape(package['kind'])}`",
                "",
                f"**Purpose:** {_escape(package['purpose'])}",
                "",
            ]
        )
        paths = _package_paths(root, package, main_paths)
        if package["traversal"] == "none":
            package_sections.extend(
                [
                    "The target is externally owned. This catalog records the pointer and "
                    "activation metadata but deliberately does not traverse or copy its files.",
                    "",
                ]
            )
            continue
        package_sections.extend(["| Package file | Role |", "|---|---|"])
        package_sections.extend(
            f"| [{_escape(path)}]({_link_from_human(path)}) | {_package_file_role(path)} |"
            for path in paths
        )
        package_sections.append("")

    hidden = sum(route["state"] == "hidden" for route in manifest["routes"])
    deprecated = sum(route["state"] == "deprecated" for route in manifest["routes"])
    return (
        "---\n"
        "audience: human\n"
        "authority: generated-explanatory-only\n"
        "agent_read_policy: explicit-human-guide-task-or-doc-sync-only\n"
        "generated: true\n"
        "---\n\n"
        f"{GENERATED_NOTICE}\n\n"
        "# Live Skill Catalog\n\n"
        "Back to [skill anatomy](09_SKILL_ANATOMY.md). This page is generated from "
        "the canonical registry and declared package boundaries. It never loads a skill "
        "body into ordinary routing. Hidden and deprecated identifiers remain omitted "
        f"outside maintenance; current counts are {hidden} hidden and {deprecated} deprecated.\n\n"
        "| Skill | Family | State | Purpose | Trigger | Not for | Structure | Source | Approx. tokens |\n"
        "|---|---|---|---|---|---|---|---|---:|\n"
        + "\n".join(rows)
        + "\n\n# Package Contents\n\n"
        + "\n".join(package_sections)
    )


def render_outputs(root: Path = ROOT) -> dict[str, str]:
    model = load_model(root)
    contract = load_contract(root)
    manifest = build_manifest(root)
    outputs = render_agent_entries(root, model)
    outputs[model["human_outputs"]["repository_index"]] = render_repository_index(
        root, model, contract, manifest
    )
    outputs[model["human_outputs"]["skill_catalog"]] = render_skill_catalog(
        root, model, manifest
    )
    return dict(sorted(outputs.items()))


def stale_outputs(root: Path = ROOT) -> list[str]:
    stale: list[str] = []
    for relative, expected in render_outputs(root).items():
        path = root / relative
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError:
            actual = ""
        if actual != expected:
            stale.append(relative)
    return stale


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when a generated view is stale")
    args = parser.parse_args(argv)
    try:
        outputs = render_outputs()
        if args.check:
            stale = [
                relative
                for relative, content in outputs.items()
                if not (ROOT / relative).is_file()
                or (ROOT / relative).read_text(encoding="utf-8") != content
            ]
            if stale:
                print("stale: " + ", ".join(stale))
                return 1
            print(f"ok: {len(outputs)} generated repository views")
            return 0
        for relative, content in outputs.items():
            atomic_write(ROOT / relative, content)
        print(f"generated: {len(outputs)} repository views")
        return 0
    except (OSError, ValueError, RuntimeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
