#!/usr/bin/env python3
"""Generate shared agent entries, generated references and inventory graph nodes."""

from __future__ import annotations

import argparse
import ast
import json
import math
import re
import subprocess
import sys
from pathlib import Path
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from change_guard import _matches_pattern, load_contract, matching_roles  # noqa: E402
from compile_registry import atomic_write  # noqa: E402
from registry_runtime import build_manifest
from model_context import capability_records  # noqa: E402


MODEL_PATH = Path("protocols/repository/DOCUMENTATION.json")
GENERATED_NOTICE = "<!-- Generated by scripts/compile_repository_views.py. Do not edit directly. -->"
MAX_SUMMARY_CHARS = 180


class ViewError(RuntimeError):
    pass


def load_model(root: Path = ROOT) -> dict[str, Any]:
    try:
        model = json.loads((root / MODEL_PATH).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ViewError(f"cannot read {MODEL_PATH}: {type(exc).__name__}") from exc
    if model.get("version") != 1:
        raise ViewError("unsupported documentation model version")
    for key in ("areas", "agent_entries", "generated_references", "orchestrator", "packages"):
        if key not in model:
            raise ViewError(f"documentation model is missing {key}")
    return model


def _git_paths(root: Path, *args: str) -> list[str]:
    completed = subprocess.run(
        ["git", *args, "-z"], cwd=root, capture_output=True, check=False
    )
    if completed.returncode:
        message = completed.stderr.decode("utf-8", errors="replace").strip()
        raise ViewError(message or f"git {' '.join(args)} failed")
    return sorted(
        item
        for item in completed.stdout.decode("utf-8", errors="surrogateescape").split("\0")
        if item
    )


def _excluded(path: str, model: dict[str, Any]) -> bool:
    return any(_matches_pattern(path, pattern) for pattern in model.get("exclusions", []))


def repository_paths(root: Path, model: dict[str, Any]) -> list[str]:
    # Generated references describe tracked files plus untracked additions that already
    # resolve to a declared repository role. Arbitrary scratch files therefore
    # cannot make generated documentation stale, while a legitimate new source
    # can enter the maintenance transaction before it is staged.
    paths = {
        path
        for path in _git_paths(root, "ls-files")
        if (root / path).exists() or (root / path).is_symlink()
    }
    contract = load_contract(root)
    paths.update(
        path
        for path in _git_paths(root, "ls-files", "--others", "--exclude-standard")
        if matching_roles(path, contract)
    )
    paths.add(MODEL_PATH.as_posix())
    paths.add(Path(__file__).relative_to(root).as_posix())
    paths.add(model["agent_entries"]["common"])
    paths.update(model["agent_entries"]["outputs"].keys())
    paths.update(model["agent_entries"]["outputs"].values())
    paths.update(model["generated_references"].values())
    paths.add(model["orchestrator"]["graph_entry"])
    paths.update(package["graph_entry"] for package in model["packages"])
    for package in model["packages"]:
        if package.get("traversal") != "declared-submodule":
            continue
        prefix = package["path"].rstrip("/")
        submodule = root / prefix
        if not submodule.is_dir():
            raise ViewError(f"declared submodule is unavailable: {prefix}")
        paths.update(f"{prefix}/{path}" for path in _git_paths(submodule, "ls-files"))
    return sorted(path for path in paths if not _excluded(path, model))


def _strip_frontmatter(text: str) -> str:
    if not text.startswith("---\n"):
        return text.strip()
    end = text.find("\n---\n", 4)
    if end < 0:
        raise ViewError("entry source has unclosed YAML frontmatter")
    return text[end + 5 :].strip()


def _clean_summary(text: str) -> str:
    cleaned = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    cleaned = re.sub(r"\[\[([^\]|]+)(?:\|[^\]]+)?\]\]", r"\1", cleaned)
    cleaned = re.sub(r"[`*#>]", "", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    if len(cleaned) > MAX_SUMMARY_CHARS:
        cleaned = cleaned[: MAX_SUMMARY_CHARS - 1].rstrip() + "…"
    return cleaned


def _markdown_summary(path: Path) -> str | None:
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None
    body = _strip_frontmatter(text) if text.startswith("---\n") else text
    heading = re.search(r"^#\s+(.+)$", body, flags=re.MULTILINE)
    body = re.sub(r"```.*?```", "", body, flags=re.DOTALL)
    paragraphs = re.split(r"\n\s*\n", body)
    explanation = ""
    for paragraph in paragraphs:
        value = paragraph.strip()
        if not value or value.startswith(("#", "```", "<!--", "Back:", "Back to", "Return to")):
            continue
        explanation = value
        break
    parts = [heading.group(1) if heading else "", explanation]
    summary = _clean_summary(" — ".join(part for part in parts if part))
    return summary or None


def _python_summary(path: Path) -> str | None:
    try:
        module = ast.parse(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, SyntaxError):
        return None
    doc = ast.get_docstring(module, clean=True)
    return _clean_summary(doc.splitlines()[0]) if doc else None


def _javascript_summary(path: Path) -> str | None:
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None
    match = re.search(r"/\*\*?\s*(.*?)\*/", text, flags=re.DOTALL)
    return _clean_summary(match.group(1)) if match else None


def _area(path: str, model: dict[str, Any]) -> dict[str, str] | None:
    matches = [
        area
        for area in model["areas"]
        if path == area["path"] or path.startswith(area["path"].rstrip("/") + "/")
    ]
    return max(matches, key=lambda item: len(item["path"])) if matches else None


def _purpose(
    relative: str,
    *,
    root: Path,
    model: dict[str, Any],
    route_by_path: dict[str, dict[str, Any]],
) -> str:
    override = model.get("artifact_overrides", {}).get(relative)
    if override:
        return override
    route = route_by_path.get(relative)
    if route:
        return route["description"]
    path = root / relative
    if path.is_symlink():
        area = _area(relative, model)
        return area["purpose"] if area else "Declared symbolic-link entry."
    if path.is_file():
        summary = None
        if path.suffix.lower() == ".md":
            summary = _markdown_summary(path)
        elif path.suffix.lower() == ".py":
            summary = _python_summary(path)
        elif path.suffix.lower() == ".js":
            summary = _javascript_summary(path)
        if summary:
            return summary
    area = _area(relative, model)
    if area:
        return area["purpose"]
    if relative.startswith("."):
        return "Repository configuration or support metadata."
    raise ViewError(f"no explanation can be derived for repository path: {relative}")


def _inventory_units(model: dict[str, Any]) -> list[dict[str, Any]]:
    return [model["orchestrator"], *model["packages"]]


def _package_for_path(path: str, model: dict[str, Any]) -> dict[str, Any] | None:
    matches = [
        package
        for package in _inventory_units(model)
        if path == package["path"] or path.startswith(package["path"].rstrip("/") + "/")
    ]
    return max(matches, key=lambda package: len(package["path"])) if matches else None


def _is_external_pointer(path: str, model: dict[str, Any]) -> bool:
    package = _package_for_path(path, model)
    return bool(package and package.get("traversal") == "none")


def _kind(path: str, generated: set[str], roles: list[str], model: dict[str, Any]) -> str:
    if path in generated:
        return "generated"
    package = _package_for_path(path, model)
    if package and package.get("traversal") == "declared-submodule":
        return "submodule"
    if _is_external_pointer(path, model):
        return "external pointer"
    if "skill-source" in roles:
        return "skill source"
    if "test-source" in roles:
        return "verification"
    if path.endswith(("CONTRACT.json", "DOCUMENTATION.json")):
        return "canonical contract"
    return "source/support"


def _escape(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def _link_from_reference(path: str) -> str:
    return f"../../{path}"


def _file_cell(path: str, model: dict[str, Any]) -> str:
    if _is_external_pointer(path, model):
        return f"`{_escape(path)}`"
    return f"[{_escape(path)}]({_link_from_reference(path)})"


def render_agent_entries(root: Path, model: dict[str, Any]) -> dict[str, str]:
    common_path = root / model["agent_entries"]["common"]
    common = _strip_frontmatter(common_path.read_text(encoding="utf-8"))
    outputs: dict[str, str] = {}
    for output, overlay_path in sorted(model["agent_entries"]["outputs"].items()):
        overlay = _strip_frontmatter((root / overlay_path).read_text(encoding="utf-8"))
        outputs[output] = (
            f"{GENERATED_NOTICE}\n\n{common.rstrip()}\n\n{overlay.rstrip()}\n"
        )
    return outputs


def render_repository_index(
    root: Path,
    model: dict[str, Any],
    contract: dict[str, Any],
    manifest: dict[str, Any],
) -> str:
    generated = {
        *model["agent_entries"]["outputs"].keys(),
        *model["generated_references"].values(),
        *contract.get("generated_outputs", {}).keys(),
    }
    route_by_path = {route["path"]: route for route in manifest["routes"]}
    rows: list[str] = []
    for relative in repository_paths(root, model):
        roles = [role["id"] for role in matching_roles(relative, contract)]
        purpose = _purpose(
            relative, root=root, model=model, route_by_path=route_by_path
        )
        role_text = ", ".join(roles) if roles else "repository-contained"
        rows.append(
            "| "
            + f"{_file_cell(relative, model)} | "
            + f"{_escape(purpose)} | {_kind(relative, generated, roles, model)} | "
            + f"{_escape(role_text)} |"
        )
    return (
        "---\n"
        "authority: generated-reference\n"
        "generated: true\n"
        "---\n\n"
        f"{GENERATED_NOTICE}\n\n"
        "# File Index\n\n"
        "Back to the [README](../../README.md). This exhaustive "
        "reference is generated from Git, the repository contract, registry metadata, "
        "file introductions, and deterministic fallbacks. It describes files but never "
        "overrides their canonical content.\n\n"
        "| File | What it means | Kind | Maintenance role |\n"
        "|---|---|---|---|\n"
        + "\n".join(rows)
        + "\n"
    )


def _capability_kind(path: str, model: dict[str, Any]) -> str:
    package = _package_for_path(path, model)
    if package and package.get("traversal") == "declared-submodule":
        return "submodule capability"
    if _is_external_pointer(path, model):
        return "external pointer"
    return "package capability"


def _token_estimate(path: Path, relative: str, model: dict[str, Any] | None = None) -> str:
    active_model = model or load_model(ROOT)
    if _is_external_pointer(relative, active_model) or path.is_symlink() or not path.is_file():
        return "—"
    return str(math.ceil(path.stat().st_size / 4))


def _package_paths(root: Path, package: dict[str, Any], main_paths: Iterable[str]) -> list[str]:
    prefix = package["path"].rstrip("/")
    traversal = package["traversal"]
    if traversal == "none":
        return []
    if traversal == "repository":
        return sorted(path for path in main_paths if path.startswith(prefix + "/"))
    if traversal == "declared-submodule":
        submodule = root / prefix
        if not submodule.is_dir():
            raise ViewError(f"declared submodule is unavailable: {prefix}")
        return [f"{prefix}/{path}" for path in _git_paths(submodule, "ls-files")]
    raise ViewError(f"unsupported package traversal: {traversal}")


def _package_file_role(path: str) -> str:
    name = Path(path).name
    if name == "README.md":
        return "Orientation for the package."
    if name == "SKILL.md":
        return "Skill entry or shared workflow instructions."
    if name in {"AGENTS.md", "CLAUDE.md", "CODEX.md"} or "/codex/" in path:
        return "Platform wrapper or platform metadata."
    if "/shared/phases/" in path:
        return "Phase-specific instructions loaded only for that operation."
    if "/shared/rules/" in path:
        return "Reusable constraint shared by multiple phases."
    if "/shared/templates/" in path:
        return "Reusable output template."
    if "/scripts/" in path:
        return "Deterministic support, installation, synchronization, or validation script."
    if name == "protocol.json":
        return "Canonical machine-readable protocol."
    return "Package support file."


def _obsidian_target(path: str) -> str:
    return path[:-3] if path.endswith(".md") else path


def render_graph_entries(model: dict[str, Any], manifest: dict[str, Any]) -> dict[str, str]:
    """Generate uniquely named inventory graph nodes from canonical inventory data."""
    orchestrator = model["orchestrator"]
    live_orchestrator = manifest["orchestrator"]
    skill_links = [
        f"- [[{_obsidian_target(package['graph_entry'])}|{package['display_name']}]]"
        for package in model["packages"]
    ]
    outputs = {
        orchestrator["graph_entry"]: (
            "---\n"
            "generated: true\n"
            "graph_kind: orchestrator\n"
            f"graph_label: {json.dumps(orchestrator['display_name'])}\n"
            f"orchestrator_id: {orchestrator['id']}\n"
            "state: active\n"
            "---\n\n"
            f"{GENERATED_NOTICE}\n\n"
            f"# {orchestrator['display_name']}\n\n"
            f"{orchestrator['purpose']}\n\n"
            "Canonical control plane: "
            f"[[{_obsidian_target(live_orchestrator['path'])}|runtime instructions]]. "
            "Registry switchboard: [[registry/activation|Activation]]. "
            "Maintenance hub: [[docs/00_SKILLS_HUB|Skills Hub]].\n\n"
            "## Skills\n\n"
            + "\n".join(skill_links)
            + "\n"
        )
    }

    live_packages = manifest["packages"]
    for package in model["packages"]:
        skill_id = package["id"]
        live = live_packages[skill_id]
        family_rows = sorted(
            (family_id, family)
            for family_id, family in manifest.get("families", {}).items()
            if family.get("package") == skill_id
        )
        family_links = []
        for family_id, family in family_rows:
            if live["state"] in {"active", "manual"}:
                family_links.append(
                    f"- [[{_obsidian_target(family['path'])}|{family_id}]]"
                )
            else:
                family_links.append(f"- `{family_id}`: `{family['path']}`")
        if live["state"] in {"active", "manual"}:
            canonical_entry = f"[[{_obsidian_target(live['path'])}|canonical entry]]"
        else:
            canonical_entry = f"`{live['path']}`"
        outputs[package["graph_entry"]] = (
            "---\n"
            "generated: true\n"
            "graph_kind: skill-package\n"
            f"graph_label: {json.dumps(package['display_name'])}\n"
            f"skill_id: {skill_id}\n"
            f"state: {live['state']}\n"
            f"role: {live['role']}\n"
            "---\n\n"
            f"{GENERATED_NOTICE}\n\n"
            f"# {package['display_name']}\n\n"
            f"{package['purpose']}\n\n"
            f"**State:** `{live['state']}`\n\n"
            f"**Role:** `{live['role']}`\n\n"
            f"**Canonical entry:** {canonical_entry}\n\n"
            "Control plane: "
            f"[[{_obsidian_target(orchestrator['graph_entry'])}|Skills Orchestrator]]. "
            "Registry switchboard: [[registry/activation|Activation]].\n\n"
            "## Families\n\n"
            + ("\n".join(family_links) if family_links else "No internal family registry.")
            + "\n"
        )
    return outputs


def render_skill_catalog(root: Path, model: dict[str, Any], manifest: dict[str, Any]) -> str:
    visible_states = {"active", "manual", "off"}
    declared_orchestrator = model["orchestrator"]
    live_orchestrator = manifest.get("orchestrator", {})
    if declared_orchestrator["id"] != live_orchestrator.get("id"):
        raise ViewError(
            "documentation orchestrator declaration differs from the live manifest: "
            f"declared={declared_orchestrator['id']}, live={live_orchestrator.get('id')}"
        )
    declared_packages = {package["id"]: package for package in model["packages"]}
    manifest_packages = manifest.get("packages", {})
    if set(declared_packages) != set(manifest_packages):
        missing = sorted(set(manifest_packages) - set(declared_packages))
        extra = sorted(set(declared_packages) - set(manifest_packages))
        raise ViewError(
            "documentation package declarations differ from the live manifest: "
            f"missing={missing}, extra={extra}"
        )

    records = capability_records(root,manifest)
    package_rows: list[str] = []
    for package in model["packages"]:
        package_id = package["id"]
        live = manifest_packages[package_id]
        if live["state"] not in visible_states:
            continue
        capability_count = sum(
            route.get("package") == package_id and route["state"] in visible_states
            for route in records
        )
        task_capabilities = str(capability_count) if live["role"] == "task" else "—"
        package_rows.append(
            "| "
            + f"{_escape(package_id)} | {_escape(live['role'])} | {_escape(live['state'])} | "
            + f"{_escape(live['boundary'])} | {_escape(package['kind'])} | "
            + f"{_file_cell(live['path'], model)} | {task_capabilities} |"
        )

    capability_rows: list[str] = []
    for record in records:
        if record["state"] not in visible_states: continue
        route = next((r for r in manifest['routes'] if r['id']==record['capability']), {})
        family = route.get('family') or ', '.join(k for k,v in manifest['families'].items() if v['package']==record['package'])
        source = record['entry']
        capability_rows.append(
            "| " + f"{_escape(record['package'])} | {_escape(record['capability'])} | "
            + f"{_escape(family)} | {_escape(record['state'])} | {_escape(record['purpose'])} | "
            + f"{_escape(', '.join(route.get('triggers',[])) or 'purpose metadata')} | "
            + f"{_escape(route.get('not_for',''))} | {_capability_kind(source,model)} | "
            + f"{_file_cell(source,model)} | {_token_estimate(root/source,source,model)} |"
        )

    main_paths = repository_paths(root, model)
    orchestrator_paths = _package_paths(root, declared_orchestrator, main_paths)
    orchestrator_contents = [
        "| Orchestrator file | Role |",
        "|---|---|",
        *(
            f"| [{_escape(path)}]({_link_from_reference(path)}) | {_package_file_role(path)} |"
            for path in orchestrator_paths
        ),
    ]
    package_sections: list[str] = []
    for package in model["packages"]:
        package_sections.extend(
            [
                f"## {_escape(package['id'])}",
                "",
                f"**Type:** `{_escape(package['kind'])}`",
                "",
                f"**Purpose:** {_escape(package['purpose'])}",
                "",
            ]
        )
        paths = _package_paths(root, package, main_paths)
        if package["traversal"] == "none":
            package_sections.extend(
                [
                    "The target is externally owned. This catalog records the pointer and "
                    "activation metadata but deliberately does not traverse or copy its files.",
                    "",
                ]
            )
            continue
        package_sections.extend(["| Package file | Role |", "|---|---|"])
        package_sections.extend(
            f"| [{_escape(path)}]({_link_from_reference(path)}) | {_package_file_role(path)} |"
            for path in paths
        )
        package_sections.append("")

    hidden = sum(package["state"] == "hidden" for package in manifest_packages.values())
    deprecated = sum(package["state"] == "deprecated" for package in manifest_packages.values())
    return (
        "---\n"
        "authority: generated-reference\n"
        "generated: true\n"
        "---\n\n"
        f"{GENERATED_NOTICE}\n\n"
        "# Skill Catalog\n\n"
        "Back to the [skills registry entry](../SKILLS.md). This page is generated from "
        "the canonical registry and declared inventory boundaries. The always-active "
        "orchestrator is shown separately and never counted as a skill. Public skill inventory "
        "counts packages only; routes, modes, components, and files are internal capabilities, "
        "never additional skills. Hidden and deprecated skills remain omitted outside "
        f"maintenance; current counts are {hidden} hidden and {deprecated} deprecated.\n\n"
        "# Skills Orchestrator\n\n"
        "| Control plane | Mode | State | Structure | Entry |\n"
        "|---|---|---|---|---|\n"
        f"| {_escape(live_orchestrator['id'])} | {_escape(live_orchestrator['mode'])} | "
        f"{_escape(live_orchestrator['state'])} | {_escape(declared_orchestrator['kind'])} | "
        f"{_file_cell(live_orchestrator['path'], model)} |\n\n"
        "# Public Skills\n\n"
        "| Public skill | Role | State | Boundary | Structure | Entry | Task capabilities |\n"
        "|---|---|---|---|---|---|---:|\n"
        + "\n".join(package_rows)
        + "\n\n# Internal Capabilities\n\n"
        "These technical routes select focused instructions inside a public task package. "
        "They are not public skills and must never be added to the package count.\n\n"
        "| Package | Capability | Family | State | Purpose | Trigger | Not for | Structure | Source | Approx. tokens |\n"
        "|---|---|---|---|---|---|---|---|---|---:|\n"
        + "\n".join(capability_rows)
        + "\n\n# Orchestrator Contents\n\n"
        + "\n".join(orchestrator_contents)
        + "\n\n# Skill Contents\n\n"
        + "\n".join(package_sections)
    )


def render_outputs(root: Path = ROOT) -> dict[str, str]:
    model = load_model(root)
    contract = load_contract(root)
    manifest = build_manifest(root)
    outputs = render_agent_entries(root, model)
    outputs[model["generated_references"]["repository_index"]] = render_repository_index(
        root, model, contract, manifest
    )
    outputs[model["generated_references"]["skill_catalog"]] = render_skill_catalog(
        root, model, manifest
    )
    outputs.update(render_graph_entries(model, manifest))
    return dict(sorted(outputs.items()))


def stale_outputs(root: Path = ROOT) -> list[str]:
    stale: list[str] = []
    for relative, expected in render_outputs(root).items():
        path = root / relative
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError:
            actual = ""
        if actual != expected:
            stale.append(relative)
    return stale


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when a generated view is stale")
    args = parser.parse_args(argv)
    try:
        outputs = render_outputs()
        if args.check:
            stale = [
                relative
                for relative, content in outputs.items()
                if not (ROOT / relative).is_file()
                or (ROOT / relative).read_text(encoding="utf-8") != content
            ]
            if stale:
                print("stale: " + ", ".join(stale))
                return 1
            print(f"ok: {len(outputs)} generated repository views")
            return 0
        for relative, content in outputs.items():
            atomic_write(ROOT / relative, content)
        print(f"generated: {len(outputs)} repository views")
        return 0
    except (OSError, ValueError, RuntimeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
