#!/usr/bin/env python3
"""Validate the derivative human guide and its staged update coverage."""

from __future__ import annotations

import argparse
import fnmatch
import json
import re
import subprocess
from pathlib import Path
from typing import Any, Iterable

from change_guard import GuardError, load_contract, split_scope


ROOT = Path(__file__).resolve().parents[1]
SOURCE_MAP_PATH = Path("docs/human/_SOURCE_MAP.json")
AGENT_ENTRY_PATHS = (Path("AGENTS.md"), Path("CLAUDE.md"))
MANIFEST_PATH = Path("runtime/router-manifest.json")
HUMAN_BOUNDARY_TEXT = "`README.md` and `docs/human/` are human-facing explanations."
GENERATED_NOTICE = "<!-- Generated by scripts/compile_repository_views.py. Do not edit directly. -->"


class HumanDocsError(RuntimeError):
    pass


def load_source_map(root: Path = ROOT) -> dict[str, Any]:
    path = root / SOURCE_MAP_PATH
    try:
        config = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise HumanDocsError(f"cannot read {SOURCE_MAP_PATH}: {type(exc).__name__}") from exc
    if config.get("version") != 3:
        raise HumanDocsError("unsupported human-doc source-map version")
    if not isinstance(config.get("human_entry"), str):
        raise HumanDocsError("human_entry must be a path string")
    if not isinstance(config.get("required_marker"), str):
        raise HumanDocsError("required_marker must be a string")
    if not isinstance(config.get("rules"), list) or not config["rules"]:
        raise HumanDocsError("rules must be a non-empty list")
    if not isinstance(config.get("generated_guides"), list):
        raise HumanDocsError("generated_guides must be a list")
    limits = config.get("mermaid_limits")
    if not isinstance(limits, dict):
        raise HumanDocsError("mermaid_limits must be an object")
    for key in ("max_nodes", "max_edges", "max_lr_nodes"):
        if not isinstance(limits.get(key), int) or limits[key] < 1:
            raise HumanDocsError(f"mermaid_limits.{key} must be a positive integer")
    return config


def _matches(path: str, pattern: str) -> bool:
    return fnmatch.fnmatchcase(path, pattern)


def _normalized_relative(raw_path: str) -> str:
    path = Path(raw_path).as_posix()
    return path[2:] if path.startswith("./") else path


def guide_paths(config: dict[str, Any]) -> list[str]:
    paths = {config["human_entry"]}
    for rule in config["rules"]:
        paths.update(rule.get("guides", []))
    return sorted(paths)


def required_guides(changed_paths: Iterable[str], config: dict[str, Any]) -> dict[str, list[str]]:
    required: dict[str, set[str]] = {}
    for raw_path in changed_paths:
        path = _normalized_relative(raw_path)
        for rule in config["rules"]:
            if any(_matches(path, pattern) for pattern in rule.get("sources", [])):
                for guide in rule.get("guides", []):
                    required.setdefault(guide, set()).add(rule["name"])
    return {guide: sorted(names) for guide, names in sorted(required.items())}


def coverage_errors(changed_paths: Iterable[str], config: dict[str, Any]) -> list[str]:
    changed = {_normalized_relative(path) for path in changed_paths}
    generated = {_normalized_relative(path) for path in config.get("generated_guides", [])}
    errors: list[str] = []
    for guide, rule_names in required_guides(changed, config).items():
        # Generated guides are checked byte-for-byte by the repository-view
        # compiler. Requiring a hand change here creates an impossible cycle
        # when regeneration correctly produces identical output.
        if guide in generated:
            continue
        if guide not in changed:
            errors.append(
                f"mapped human page not changed: {guide} "
                f"(required by {', '.join(rule_names)})"
            )
    return errors


def _mermaid_errors(text: str, relative: str, limits: dict[str, int]) -> list[str]:
    errors: list[str] = []
    for match in re.finditer(r"```mermaid\s*\n(.*?)```", text, flags=re.DOTALL):
        body = match.group(1)
        line_number = text.count("\n", 0, match.start()) + 1
        nodes = set(re.findall(r"\b([A-Za-z][A-Za-z0-9_]*)\s*(?=\[|\{|\()", body))
        edge_count = sum(line.count("->") for line in body.splitlines())
        direction = re.search(r"^\s*(?:flowchart|graph)\s+(LR|RL|TD|TB)\b", body, re.MULTILINE)
        if len(nodes) > limits["max_nodes"]:
            errors.append(
                f"Mermaid diagram has {len(nodes)} nodes, limit {limits['max_nodes']}, "
                f"in {relative}:{line_number}; split it into focused diagrams"
            )
        if edge_count > limits["max_edges"]:
            errors.append(
                f"Mermaid diagram has {edge_count} edges, limit {limits['max_edges']}, "
                f"in {relative}:{line_number}; split it into focused diagrams"
            )
        if direction and direction.group(1) in {"LR", "RL"} and len(nodes) > limits["max_lr_nodes"]:
            errors.append(
                f"wide Mermaid diagram has {len(nodes)} nodes, limit {limits['max_lr_nodes']}, "
                f"in {relative}:{line_number}; use TD/TB or split the flow"
            )
    return errors


def _validate_markdown(
    path: Path,
    root: Path,
    marker: str,
    limits: dict[str, int],
) -> list[str]:
    relative = path.relative_to(root).as_posix()
    errors: list[str] = []
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        return [f"cannot read human page {relative}: {type(exc).__name__}"]
    if marker not in text[:500]:
        errors.append(f"human page missing marker {marker!r}: {relative}")

    fence: tuple[int, str] | None = None
    for line_number, line in enumerate(text.splitlines(), start=1):
        if not line.startswith("```"):
            continue
        if fence is None:
            fence = (line_number, line[3:].strip())
        else:
            fence = None
    if fence is not None:
        errors.append(f"unclosed {fence[1] or 'code'} fence in {relative}:{fence[0]}")
    errors.extend(_mermaid_errors(text, relative, limits))

    for target in re.findall(r"(?<!!)\[[^\]]+\]\(([^)]+)\)", text):
        destination = target.strip().strip("<>").split("#", 1)[0]
        if not destination or re.match(r"^[a-z]+://", destination) or destination.startswith("mailto:"):
            continue
        resolved = (path.parent / destination).resolve(strict=False)
        try:
            resolved.relative_to(root.resolve())
        except ValueError:
            errors.append(f"human link escapes repository in {relative}: {target}")
            continue
        if not resolved.exists():
            errors.append(f"broken human link in {relative}: {target}")
    return errors


def validate_human_docs(root: Path = ROOT) -> list[str]:
    try:
        config = load_source_map(root)
    except HumanDocsError as exc:
        return [str(exc)]
    errors: list[str] = []
    marker = config["required_marker"]
    limits = config["mermaid_limits"]
    names: set[str] = set()
    for index, rule in enumerate(config["rules"]):
        name = rule.get("name")
        if not isinstance(name, str) or not name:
            errors.append(f"rule {index} has no name")
        elif name in names:
            errors.append(f"duplicate source-map rule: {name}")
        else:
            names.add(name)
        if not rule.get("sources") or not rule.get("guides"):
            errors.append(f"source-map rule has empty sources or guides: {name or index}")
        for pattern in rule.get("sources", []):
            if not list(root.glob(pattern)):
                errors.append(f"source-map pattern matches nothing: {pattern}")

    for relative in guide_paths(config):
        path = root / relative
        if not path.is_file():
            errors.append(f"human page does not exist: {relative}")
            continue
        errors.extend(_validate_markdown(path, root, marker, limits))

    for relative in config["generated_guides"]:
        path = root / relative
        if not path.is_file():
            errors.append(f"generated human page does not exist: {relative}")
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except OSError as exc:
            errors.append(f"cannot read generated human page {relative}: {type(exc).__name__}")
            continue
        if GENERATED_NOTICE not in text[:500]:
            errors.append(f"generated human page is missing its source notice: {relative}")

    for entry_path in AGENT_ENTRY_PATHS:
        try:
            entry = (root / entry_path).read_text(encoding="utf-8")
        except OSError as exc:
            errors.append(f"cannot read {entry_path}: {type(exc).__name__}")
            continue
        if HUMAN_BOUNDARY_TEXT not in entry:
            errors.append(f"agent entry is missing the human-guide boundary: {entry_path}")

    try:
        manifest = (root / MANIFEST_PATH).read_text(encoding="utf-8")
    except OSError as exc:
        errors.append(f"cannot read {MANIFEST_PATH}: {type(exc).__name__}")
    else:
        if "docs/human/" in manifest or '"path": "README.md"' in manifest:
            errors.append("human guide leaked into the runtime manifest")
    return errors


def _scoped_worktree_paths(
    paths: Iterable[str],
    *,
    allowed_paths: Iterable[str],
    contract: dict[str, Any],
) -> list[str]:
    changes = [
        {"status": "?", "path": path, "source": "working-tree"}
        for path in paths
        if path
    ]
    scoped, _, _ = split_scope(changes, allowed_paths, contract)
    return sorted(change["path"] for change in scoped)


def git_changed_paths(
    root: Path = ROOT,
    *,
    staged: bool,
    allowed_paths: Iterable[str] = (),
) -> list[str]:
    command = ["git", "diff"]
    if staged:
        command.append("--cached")
    command.extend(["--name-only", "--diff-filter=ACMRD"])
    completed = subprocess.run(command, cwd=root, text=True, capture_output=True, check=False)
    if completed.returncode:
        raise HumanDocsError(completed.stderr.strip() or "cannot inspect Git changes")
    paths = set(completed.stdout.splitlines())
    if not staged:
        untracked = subprocess.run(
            ["git", "ls-files", "--others", "--exclude-standard"],
            cwd=root,
            text=True,
            capture_output=True,
            check=False,
        )
        if untracked.returncode:
            raise HumanDocsError(untracked.stderr.strip() or "cannot inspect untracked files")
        paths.update(untracked.stdout.splitlines())
    changed = sorted(path for path in paths if path)
    if staged:
        return changed
    try:
        contract = load_contract(root)
    except GuardError as exc:
        raise HumanDocsError(str(exc)) from exc
    return _scoped_worktree_paths(
        changed,
        allowed_paths=allowed_paths,
        contract=contract,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group()
    action.add_argument("--check", action="store_true", help="validate structure and boundaries")
    action.add_argument("--check-staged", action="store_true", help="also require staged source-to-guide coverage")
    action.add_argument("--check-changed", action="store_true", help="also require working-tree source-to-guide coverage")
    parser.add_argument(
        "--path",
        action="append",
        default=[],
        dest="paths",
        help="approved working-tree scope; repeat for multiple paths",
    )
    args = parser.parse_args(argv)

    errors = validate_human_docs()
    changed: list[str] = []
    try:
        if args.check_staged:
            changed = git_changed_paths(staged=True)
        elif args.check_changed:
            changed = git_changed_paths(staged=False, allowed_paths=args.paths)
        if changed:
            errors.extend(coverage_errors(changed, load_source_map()))
    except HumanDocsError as exc:
        errors.append(str(exc))

    if errors:
        for error in errors:
            print(f"error: {error}")
        return 1
    print(
        f"ok: human guide structure and boundaries"
        + (f"; {len(changed)} changed paths covered" if changed else "")
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
